//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded
public class VSD_Zuzahlungsstatus {
    
    public static let namespacePrefix: String? = "VSD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/vsdm/vsd/v5.2"
    
    // attributes:
    
    // elements:
    public var Status: Int
    public var Gueltig_bis: String?
    
    // default Constructor
    public init() {
        
        self.Status = Int()
        self.Gueltig_bis = nil
        
    }
    
    // copy Constructor
    public init(_ _VSD_Zuzahlungsstatus: VSD_Zuzahlungsstatus ) {
        
        self.Status = _VSD_Zuzahlungsstatus.Status
        self.Gueltig_bis = _VSD_Zuzahlungsstatus.Gueltig_bis
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> VSD_Zuzahlungsstatus {
        
        let _VSD_Zuzahlungsstatus = VSD_Zuzahlungsstatus()
        
        let uriStatus = Int.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameStatus = QName("Status", uri: uriStatus)
        _VSD_Zuzahlungsstatus.Status = Int.deserialize(infoset.select(qNameStatus))
        
        let uriGueltig_bis = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameGueltig_bis = QName("Gueltig_bis", uri: uriGueltig_bis)
        _VSD_Zuzahlungsstatus.Gueltig_bis = String?.deserialize(infoset.select(qNameGueltig_bis))
        
        return _VSD_Zuzahlungsstatus
    }
}

extension Optional where Wrapped == VSD_Zuzahlungsstatus {
    public static func deserialize(_ infoset: Infoset) -> VSD_Zuzahlungsstatus? {
        if infoset.count == 0 {
            return nil
        } else {
            return VSD_Zuzahlungsstatus.deserialize(infoset)
        }
    }
}

extension Array where Element: VSD_Zuzahlungsstatus {
    public var namespaceUri: String? {
        get {
            return VSD_Zuzahlungsstatus.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [VSD_Zuzahlungsstatus] {
        return infoset.map { (element: Infoset) in
        VSD_Zuzahlungsstatus.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

