//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded
public class VSD_KostentraegerType {
    
    public static let namespacePrefix: String? = "VSD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/vsdm/vsd/v5.2"
    
    // attributes:
    
    // elements:
    public var Kostentraegerkennung: Int
    public var Kostentraegerlaendercode: String
    public var Name: String
    
    // default Constructor
    public init() {
        
        self.Kostentraegerkennung = Int()
        self.Kostentraegerlaendercode = String()
        self.Name = String()
        
    }
    
    // copy Constructor
    public init(_ _VSD_KostentraegerType: VSD_KostentraegerType ) {
        
        self.Kostentraegerkennung = _VSD_KostentraegerType.Kostentraegerkennung
        self.Kostentraegerlaendercode = _VSD_KostentraegerType.Kostentraegerlaendercode
        self.Name = _VSD_KostentraegerType.Name
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> VSD_KostentraegerType {
        
        let _VSD_KostentraegerType = VSD_KostentraegerType()
        
        let uriKostentraegerkennung = Int.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameKostentraegerkennung = QName("Kostentraegerkennung", uri: uriKostentraegerkennung)
        _VSD_KostentraegerType.Kostentraegerkennung = Int.deserialize(infoset.select(qNameKostentraegerkennung))
        
        let uriKostentraegerlaendercode = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameKostentraegerlaendercode = QName("Kostentraegerlaendercode", uri: uriKostentraegerlaendercode)
        _VSD_KostentraegerType.Kostentraegerlaendercode = String.deserialize(infoset.select(qNameKostentraegerlaendercode))
        
        let uriName = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameName = QName("Name", uri: uriName)
        _VSD_KostentraegerType.Name = String.deserialize(infoset.select(qNameName))
        
        return _VSD_KostentraegerType
    }
}

extension Optional where Wrapped == VSD_KostentraegerType {
    public static func deserialize(_ infoset: Infoset) -> VSD_KostentraegerType? {
        if infoset.count == 0 {
            return nil
        } else {
            return VSD_KostentraegerType.deserialize(infoset)
        }
    }
}

extension Array where Element: VSD_KostentraegerType {
    public var namespaceUri: String? {
        get {
            return VSD_KostentraegerType.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [VSD_KostentraegerType] {
        return infoset.map { (element: Infoset) in
        VSD_KostentraegerType.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

