//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded
public class VSD_UC_GeschuetzteVersichertendatenXML {
    
    public static let namespacePrefix: String? = "VSD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/vsdm/vsd/v5.2"
    
    // attributes:
    public var CDM_VERSION: String
    
    // elements:
    public var Zuzahlungsstatus: VSD_Zuzahlungsstatus
    public var BesonderePersonengruppe: Int?
    public var DMP_Kennzeichnung: Int?
    public var Selektivvertraege: VSD_Selektivvertraege
    public var RuhenderLeistungsanspruch: VSD_RuhenderLeistungsanspruch?
    
    // default Constructor
    public init() {
        
        self.CDM_VERSION = String()
        
        self.Zuzahlungsstatus = VSD_Zuzahlungsstatus()
        self.BesonderePersonengruppe = nil
        self.DMP_Kennzeichnung = nil
        self.Selektivvertraege = VSD_Selektivvertraege()
        self.RuhenderLeistungsanspruch = nil
        
    }
    
    // copy Constructor
    public init(_ _VSD_UC_GeschuetzteVersichertendatenXML: VSD_UC_GeschuetzteVersichertendatenXML ) {
        
        self.CDM_VERSION = _VSD_UC_GeschuetzteVersichertendatenXML.CDM_VERSION
        
        self.Zuzahlungsstatus = _VSD_UC_GeschuetzteVersichertendatenXML.Zuzahlungsstatus
        self.BesonderePersonengruppe = _VSD_UC_GeschuetzteVersichertendatenXML.BesonderePersonengruppe
        self.DMP_Kennzeichnung = _VSD_UC_GeschuetzteVersichertendatenXML.DMP_Kennzeichnung
        self.Selektivvertraege = _VSD_UC_GeschuetzteVersichertendatenXML.Selektivvertraege
        self.RuhenderLeistungsanspruch = _VSD_UC_GeschuetzteVersichertendatenXML.RuhenderLeistungsanspruch
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> VSD_UC_GeschuetzteVersichertendatenXML {
        
        let _VSD_UC_GeschuetzteVersichertendatenXML = VSD_UC_GeschuetzteVersichertendatenXML()
        
        _VSD_UC_GeschuetzteVersichertendatenXML.CDM_VERSION = String.deserialize(infoset.attr("CDM_VERSION"))
        
        let uriZuzahlungsstatus = VSD_Zuzahlungsstatus.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameZuzahlungsstatus = QName("Zuzahlungsstatus", uri: uriZuzahlungsstatus)
        _VSD_UC_GeschuetzteVersichertendatenXML.Zuzahlungsstatus = VSD_Zuzahlungsstatus.deserialize(infoset.select(qNameZuzahlungsstatus))
        
        let uriBesonderePersonengruppe = Int.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameBesonderePersonengruppe = QName("BesonderePersonengruppe", uri: uriBesonderePersonengruppe)
        _VSD_UC_GeschuetzteVersichertendatenXML.BesonderePersonengruppe = Int?.deserialize(infoset.select(qNameBesonderePersonengruppe))
        
        let uriDMP_Kennzeichnung = Int.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDMP_Kennzeichnung = QName("DMP_Kennzeichnung", uri: uriDMP_Kennzeichnung)
        _VSD_UC_GeschuetzteVersichertendatenXML.DMP_Kennzeichnung = Int?.deserialize(infoset.select(qNameDMP_Kennzeichnung))
        
        let uriSelektivvertraege = VSD_Selektivvertraege.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameSelektivvertraege = QName("Selektivvertraege", uri: uriSelektivvertraege)
        _VSD_UC_GeschuetzteVersichertendatenXML.Selektivvertraege = VSD_Selektivvertraege.deserialize(infoset.select(qNameSelektivvertraege))
        
        let uriRuhenderLeistungsanspruch = VSD_RuhenderLeistungsanspruch.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameRuhenderLeistungsanspruch = QName("RuhenderLeistungsanspruch", uri: uriRuhenderLeistungsanspruch)
        _VSD_UC_GeschuetzteVersichertendatenXML.RuhenderLeistungsanspruch = VSD_RuhenderLeistungsanspruch?.deserialize(infoset.select(qNameRuhenderLeistungsanspruch))
        
        return _VSD_UC_GeschuetzteVersichertendatenXML
    }
}

extension Optional where Wrapped == VSD_UC_GeschuetzteVersichertendatenXML {
    public static func deserialize(_ infoset: Infoset) -> VSD_UC_GeschuetzteVersichertendatenXML? {
        if infoset.count == 0 {
            return nil
        } else {
            return VSD_UC_GeschuetzteVersichertendatenXML.deserialize(infoset)
        }
    }
}

extension Array where Element: VSD_UC_GeschuetzteVersichertendatenXML {
    public var namespaceUri: String? {
        get {
            return VSD_UC_GeschuetzteVersichertendatenXML.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [VSD_UC_GeschuetzteVersichertendatenXML] {
        return infoset.map { (element: Infoset) in
        VSD_UC_GeschuetzteVersichertendatenXML.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

