//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded
public class VSD_Zusatzinfos_Abrechnung_GKV {
    
    public static let namespacePrefix: String? = "VSD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/vsdm/vsd/v5.2"
    
    // attributes:
    
    // elements:
    public var Kostenerstattung: VSD_Kostenerstattung?
    public var WOP: String
    
    // default Constructor
    public init() {
        
        self.Kostenerstattung = nil
        self.WOP = String()
        
    }
    
    // copy Constructor
    public init(_ _VSD_Zusatzinfos_Abrechnung_GKV: VSD_Zusatzinfos_Abrechnung_GKV ) {
        
        self.Kostenerstattung = _VSD_Zusatzinfos_Abrechnung_GKV.Kostenerstattung
        self.WOP = _VSD_Zusatzinfos_Abrechnung_GKV.WOP
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> VSD_Zusatzinfos_Abrechnung_GKV {
        
        let _VSD_Zusatzinfos_Abrechnung_GKV = VSD_Zusatzinfos_Abrechnung_GKV()
        
        let uriKostenerstattung = VSD_Kostenerstattung.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameKostenerstattung = QName("Kostenerstattung", uri: uriKostenerstattung)
        _VSD_Zusatzinfos_Abrechnung_GKV.Kostenerstattung = VSD_Kostenerstattung?.deserialize(infoset.select(qNameKostenerstattung))
        
        let uriWOP = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameWOP = QName("WOP", uri: uriWOP)
        _VSD_Zusatzinfos_Abrechnung_GKV.WOP = String.deserialize(infoset.select(qNameWOP))
        
        return _VSD_Zusatzinfos_Abrechnung_GKV
    }
}

extension Optional where Wrapped == VSD_Zusatzinfos_Abrechnung_GKV {
    public static func deserialize(_ infoset: Infoset) -> VSD_Zusatzinfos_Abrechnung_GKV? {
        if infoset.count == 0 {
            return nil
        } else {
            return VSD_Zusatzinfos_Abrechnung_GKV.deserialize(infoset)
        }
    }
}

extension Array where Element: VSD_Zusatzinfos_Abrechnung_GKV {
    public var namespaceUri: String? {
        get {
            return VSD_Zusatzinfos_Abrechnung_GKV.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [VSD_Zusatzinfos_Abrechnung_GKV] {
        return infoset.map { (element: Infoset) in
        VSD_Zusatzinfos_Abrechnung_GKV.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

