//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded
public class VSD_Kostenerstattung {
    
    public static let namespacePrefix: String? = "VSD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/vsdm/vsd/v5.2"
    
    // attributes:
    
    // elements:
    public var AerztlicheVersorgung: String
    public var ZahnaerztlicheVersorgung: String
    public var StationaererBereich: String
    public var VeranlassteLeistungen: String
    
    // default Constructor
    public init() {
        
        self.AerztlicheVersorgung = String()
        self.ZahnaerztlicheVersorgung = String()
        self.StationaererBereich = String()
        self.VeranlassteLeistungen = String()
        
    }
    
    // copy Constructor
    public init(_ _VSD_Kostenerstattung: VSD_Kostenerstattung ) {
        
        self.AerztlicheVersorgung = _VSD_Kostenerstattung.AerztlicheVersorgung
        self.ZahnaerztlicheVersorgung = _VSD_Kostenerstattung.ZahnaerztlicheVersorgung
        self.StationaererBereich = _VSD_Kostenerstattung.StationaererBereich
        self.VeranlassteLeistungen = _VSD_Kostenerstattung.VeranlassteLeistungen
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> VSD_Kostenerstattung {
        
        let _VSD_Kostenerstattung = VSD_Kostenerstattung()
        
        let uriAerztlicheVersorgung = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameAerztlicheVersorgung = QName("AerztlicheVersorgung", uri: uriAerztlicheVersorgung)
        _VSD_Kostenerstattung.AerztlicheVersorgung = String.deserialize(infoset.select(qNameAerztlicheVersorgung))
        
        let uriZahnaerztlicheVersorgung = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameZahnaerztlicheVersorgung = QName("ZahnaerztlicheVersorgung", uri: uriZahnaerztlicheVersorgung)
        _VSD_Kostenerstattung.ZahnaerztlicheVersorgung = String.deserialize(infoset.select(qNameZahnaerztlicheVersorgung))
        
        let uriStationaererBereich = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameStationaererBereich = QName("StationaererBereich", uri: uriStationaererBereich)
        _VSD_Kostenerstattung.StationaererBereich = String.deserialize(infoset.select(qNameStationaererBereich))
        
        let uriVeranlassteLeistungen = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameVeranlassteLeistungen = QName("VeranlassteLeistungen", uri: uriVeranlassteLeistungen)
        _VSD_Kostenerstattung.VeranlassteLeistungen = String.deserialize(infoset.select(qNameVeranlassteLeistungen))
        
        return _VSD_Kostenerstattung
    }
}

extension Optional where Wrapped == VSD_Kostenerstattung {
    public static func deserialize(_ infoset: Infoset) -> VSD_Kostenerstattung? {
        if infoset.count == 0 {
            return nil
        } else {
            return VSD_Kostenerstattung.deserialize(infoset)
        }
    }
}

extension Array where Element: VSD_Kostenerstattung {
    public var namespaceUri: String? {
        get {
            return VSD_Kostenerstattung.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [VSD_Kostenerstattung] {
        return infoset.map { (element: Infoset) in
        VSD_Kostenerstattung.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

