//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded
public class VSD_Kostentraeger: VSD_KostentraegerType {
    
    // attributes:
    
    // elements:
    public var AbrechnenderKostentraeger: VSD_KostentraegerType?
    
    // default Constructor
    override public init() {
        
        self.AbrechnenderKostentraeger = nil
        
        super.init()
        
    }
    
    // copy Constructor
    public init(_ _VSD_Kostentraeger: VSD_Kostentraeger ) {
        
        self.AbrechnenderKostentraeger = _VSD_Kostentraeger.AbrechnenderKostentraeger
        
        super.init(_VSD_Kostentraeger)
        
    }
    
    // Constructor from superclass
    override public init(_ _VSD_KostentraegerType: VSD_KostentraegerType) {
        
        self.AbrechnenderKostentraeger = nil
        
        super.init(_VSD_KostentraegerType)
    }
    
    override  public class func deserialize(_ infoset: Infoset) -> VSD_Kostentraeger {
        
        let _VSD_Kostentraeger = VSD_Kostentraeger(VSD_KostentraegerType.deserialize(infoset))
        
        let uriAbrechnenderKostentraeger = VSD_KostentraegerType.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameAbrechnenderKostentraeger = QName("AbrechnenderKostentraeger", uri: uriAbrechnenderKostentraeger)
        _VSD_Kostentraeger.AbrechnenderKostentraeger = VSD_KostentraegerType?.deserialize(infoset.select(qNameAbrechnenderKostentraeger))
        
        return _VSD_Kostentraeger
    }
}

extension Optional where Wrapped == VSD_Kostentraeger {
    public static func deserialize(_ infoset: Infoset) -> VSD_Kostentraeger? {
        if infoset.count == 0 {
            return nil
        } else {
            return VSD_Kostentraeger.deserialize(infoset)
        }
    }
}

extension Array where Element: VSD_Kostentraeger {
    public var namespaceUri: String? {
        get {
            return VSD_Kostentraeger.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [VSD_Kostentraeger] {
        return infoset.map { (element: Infoset) in
        VSD_Kostentraeger.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

