//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded
public class VSD_Person {
    
    public static let namespacePrefix: String? = "VSD"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/vsdm/vsd/v5.2"
    
    // attributes:
    
    // elements:
    public var Geburtsdatum: String
    public var Vorname: String
    public var Nachname: String
    public var Geschlecht: String
    public var Vorsatzwort: String?
    public var Namenszusatz: String?
    public var Titel: String?
    public var PostfachAdresse: VSD_PostfachAdresse?
    public var StrassenAdresse: VSD_StrassenAdresse?
    
    // default Constructor
    public init() {
        
        self.Geburtsdatum = String()
        self.Vorname = String()
        self.Nachname = String()
        self.Geschlecht = String()
        self.Vorsatzwort = nil
        self.Namenszusatz = nil
        self.Titel = nil
        self.PostfachAdresse = nil
        self.StrassenAdresse = nil
        
    }
    
    // copy Constructor
    public init(_ _VSD_Person: VSD_Person ) {
        
        self.Geburtsdatum = _VSD_Person.Geburtsdatum
        self.Vorname = _VSD_Person.Vorname
        self.Nachname = _VSD_Person.Nachname
        self.Geschlecht = _VSD_Person.Geschlecht
        self.Vorsatzwort = _VSD_Person.Vorsatzwort
        self.Namenszusatz = _VSD_Person.Namenszusatz
        self.Titel = _VSD_Person.Titel
        self.PostfachAdresse = _VSD_Person.PostfachAdresse
        self.StrassenAdresse = _VSD_Person.StrassenAdresse
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> VSD_Person {
        
        let _VSD_Person = VSD_Person()
        
        let uriGeburtsdatum = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameGeburtsdatum = QName("Geburtsdatum", uri: uriGeburtsdatum)
        _VSD_Person.Geburtsdatum = String.deserialize(infoset.select(qNameGeburtsdatum))
        
        let uriVorname = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameVorname = QName("Vorname", uri: uriVorname)
        _VSD_Person.Vorname = String.deserialize(infoset.select(qNameVorname))
        
        let uriNachname = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameNachname = QName("Nachname", uri: uriNachname)
        _VSD_Person.Nachname = String.deserialize(infoset.select(qNameNachname))
        
        let uriGeschlecht = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameGeschlecht = QName("Geschlecht", uri: uriGeschlecht)
        _VSD_Person.Geschlecht = String.deserialize(infoset.select(qNameGeschlecht))
        
        let uriVorsatzwort = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameVorsatzwort = QName("Vorsatzwort", uri: uriVorsatzwort)
        _VSD_Person.Vorsatzwort = String?.deserialize(infoset.select(qNameVorsatzwort))
        
        let uriNamenszusatz = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameNamenszusatz = QName("Namenszusatz", uri: uriNamenszusatz)
        _VSD_Person.Namenszusatz = String?.deserialize(infoset.select(qNameNamenszusatz))
        
        let uriTitel = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameTitel = QName("Titel", uri: uriTitel)
        _VSD_Person.Titel = String?.deserialize(infoset.select(qNameTitel))
        
        let uriPostfachAdresse = VSD_PostfachAdresse.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNamePostfachAdresse = QName("PostfachAdresse", uri: uriPostfachAdresse)
        _VSD_Person.PostfachAdresse = VSD_PostfachAdresse?.deserialize(infoset.select(qNamePostfachAdresse))
        
        let uriStrassenAdresse = VSD_StrassenAdresse.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameStrassenAdresse = QName("StrassenAdresse", uri: uriStrassenAdresse)
        _VSD_Person.StrassenAdresse = VSD_StrassenAdresse?.deserialize(infoset.select(qNameStrassenAdresse))
        
        return _VSD_Person
    }
}

extension Optional where Wrapped == VSD_Person {
    public static func deserialize(_ infoset: Infoset) -> VSD_Person? {
        if infoset.count == 0 {
            return nil
        } else {
            return VSD_Person.deserialize(infoset)
        }
    }
}

extension Array where Element: VSD_Person {
    public var namespaceUri: String? {
        get {
            return VSD_Person.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [VSD_Person] {
        return infoset.map { (element: Infoset) in
        VSD_Person.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

